import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Free vCard QR Code Generator — Digital Business Card | Truly Free QR',
  description: 'Turn your contact info into a scannable QR business card. Free, permanent, no account required. Download in high resolution for print. Works on iPhone and Android.',
  keywords: ['vcard qr code generator', 'digital business card qr', 'contact qr code free', 'qr code business card maker', 'vcard qr free no subscription'],
  alternates: { canonical: 'https://trulyfreeqr.com/vcard-qr-code-generator' },
  openGraph: {
    title: 'Free vCard QR Code Generator — Digital Business Card',
    description: 'Create a digital business card QR code in seconds. Scan to save contact info instantly. Free forever, no account required.',
    url: 'https://trulyfreeqr.com/vcard-qr-code-generator',
    siteName: 'Truly Free QR',
    type: 'website',
  },
}

const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'SoftwareApplication',
      name: 'Truly Free QR — vCard QR Code Generator',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      url: 'https://trulyfreeqr.com/vcard-qr-code-generator',
      offers: { '@type': 'Offer', price: '0.00', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
      featureList: ['vCard QR codes free forever', 'Scan to save contact instantly', 'Works on iPhone and Android', 'High resolution PNG and SVG export', 'No account or subscription required'],
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'How do I create a vCard QR code for free?',
          acceptedAnswer: { '@type': 'Answer', text: 'Go to Truly Free QR, select the vCard tab, and enter your contact details: name, phone, email, company, and website. The QR code generates instantly. When scanned, it opens the contact save prompt on iPhone and Android automatically. Download in PNG or SVG — no account, no subscription.' },
        },
        {
          '@type': 'Question',
          name: 'What is a vCard QR code?',
          acceptedAnswer: { '@type': 'Answer', text: 'A vCard QR code encodes your contact information in the standard vCard format directly into the QR pattern. When someone scans it with their phone camera, a prompt appears to save your contact details automatically — name, phone number, email, company, and website — without manual typing.' },
        },
        {
          '@type': 'Question',
          name: 'Can I put a vCard QR code on my business card?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes. Download your vCard QR code in SVG vector format for unlimited print scaling at any resolution. Add it to your business card design in any professional design tool. When colleagues scan it at networking events, your contact details save instantly to their phone.' },
        },
        {
          '@type': 'Question',
          name: 'Does a vCard QR code expire?',
          acceptedAnswer: { '@type': 'Answer', text: 'Static vCard QR codes generated by Truly Free QR never expire. The contact data is encoded directly in the QR pattern — no server is required for it to function. Print it on 10,000 business cards with confidence that it will work permanently.' },
        },
      ],
    },
  ],
}

export default function VCardQRPage() {
  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', background: '#f7fafc', minHeight: '100vh' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />

      <nav style={{ background: '#fff', borderBottom: '1px solid rgba(74,85,104,0.15)', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 56, position: 'sticky', top: 0, zIndex: 100 }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <img src="/logo.png" alt="TrulyFreeQR" style={{height:44,width:'auto'}} />
        </Link>
        <Link href="/" style={{ background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '8px 16px', fontSize: 13, fontWeight: 600, textDecoration: 'none' }}>Generate Free QR →</Link>
      </nav>

      <div style={{ maxWidth: 860, margin: '0 auto', padding: '48px 24px 80px' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(0,88,195,0.07)', border: '1px solid rgba(0,88,195,0.2)', borderRadius: 2, padding: '4px 10px', fontSize: 11, fontWeight: 700, color: '#0058c3', letterSpacing: '0.06em', marginBottom: 16 }}>✦ FREE — PERMANENT — PRINT READY</div>
          <h1 style={{ fontSize: 36, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', lineHeight: 1.2, margin: '0 0 16px' }}>Free vCard QR Code Generator — Digital Business Card That Never Expires</h1>
          <p style={{ fontSize: 16, color: '#4a5568', lineHeight: 1.7, margin: '0 0 24px' }}>Turn your contact information into a scannable QR code in under 30 seconds. Colleagues scan with any phone camera and save your details instantly — no app, no typing. Download in PNG or SVG for print. Free forever, no account required.</p>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 28px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Create Your vCard QR Code Free →</Link>
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 16px' }}>What Information Can a vCard QR Code Store?</h2>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
            {['Full Name','Job Title','Company Name','Phone Number','Email Address','Website URL','Physical Address','LinkedIn Profile','WhatsApp Number'].map(field => (
              <div key={field} style={{ background: '#f1f4f6', borderRadius: 4, padding: '8px 12px', fontSize: 12, fontWeight: 500, color: '#4a5568', display: 'flex', alignItems: 'center', gap: 6 }}>
                <span style={{ color: '#0058c3', fontWeight: 700 }}>✓</span>{field}
              </div>
            ))}
          </div>
        </div>

        <div style={{ background: '#f1f4f6', borderRadius: 8, padding: 32, marginBottom: 32 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 20px' }}>How to Create Your vCard QR Code — 3 Steps</h2>
          {[
            ['1. Select vCard Tab', 'Go to Truly Free QR and click the vCard tab. Enter your contact details — name, phone, email, company, and website. All fields are optional except your name.'],
            ['2. Preview Instantly', 'Your QR code generates in real time as you type. Test it with your phone camera before downloading to confirm all details are correct.'],
            ['3. Download and Print', 'Download in PNG (3000×3000px) for digital use or SVG vector for business card print. Add to your business card design, email signature, or LinkedIn profile.'],
          ].map(([title, desc]) => (
            <div key={String(title)} style={{ display: 'flex', gap: 16, marginBottom: 20 }}>
              <div style={{ flexShrink: 0, width: 32, height: 32, background: 'linear-gradient(135deg,#0058c3,#0070f3)', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 13, fontWeight: 700 }}>{String(title)[0]}</div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: '#181c1e', marginBottom: 4 }}>{title}</div>
                <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.6 }}>{desc}</div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 24px' }}>Frequently Asked Questions</h2>
          {[
            ['How do I create a vCard QR code for free?', 'Go to Truly Free QR, select the vCard tab, enter your contact details. The QR code generates instantly. Download in PNG or SVG — no account, no subscription.'],
            ['What is a vCard QR code?', 'A vCard QR code encodes your contact information in the standard vCard format. When scanned, it opens a contact save prompt on iPhone and Android automatically — no manual typing required.'],
            ['Can I put a vCard QR code on my business card?', 'Yes. Download in SVG vector format for unlimited print scaling. Add to your business card design in any professional design tool.'],
            ['Does a vCard QR code expire?', 'Static vCard QR codes from Truly Free QR never expire. The data is encoded directly in the pattern — no server required. Print on 10,000 business cards with confidence.'],
          ].map(([q, a], i) => (
            <div key={i} style={{ borderTop: i === 0 ? 'none' : '1px solid rgba(74,85,104,0.1)', paddingTop: i === 0 ? 0 : 20, marginTop: i === 0 ? 0 : 20 }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#181c1e', marginBottom: 8, letterSpacing: '-0.01em' }}>{q}</div>
              <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.7 }}>{a}</div>
            </div>
          ))}
        </div>

        <div style={{ textAlign: 'center', marginTop: 48 }}>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 32px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Create Your Free vCard QR Code Now →</Link>
          <p style={{ fontSize: 12, color: '#718096', marginTop: 12 }}>No account · No credit card · No expiration · Forever free</p>
        </div>
      </div>

      <footer style={{ background: '#fff', borderTop: '1px solid rgba(74,85,104,0.15)', padding: '20px 24px', textAlign: 'center' }}>
        <div style={{ fontSize: 11, color: '#718096' }}>
          © 2026 Truly Free QR · Built by <a href="https://klickifyagency.com" target="_blank" rel="noopener noreferrer" style={{ color: '#0058c3', fontWeight: 600, textDecoration: 'none' }}>Klickify Agency</a>
        </div>
      </footer>
    </div>
  )
}
