import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Free WiFi QR Code Generator — Let Guests Connect Instantly | Truly Free QR',
  description: 'Create a WiFi QR code for free. Guests scan to connect instantly — no typing passwords. Works on iPhone and Android. Download PNG or SVG. No account required.',
  keywords: ['wifi qr code generator', 'qr code for wifi', 'wifi password qr code', 'scan to connect wifi qr', 'free wifi qr code maker'],
  alternates: { canonical: 'https://trulyfreeqr.com/wifi-qr-code-generator' },
  openGraph: {
    title: 'Free WiFi QR Code Generator — Let Guests Connect Instantly',
    description: 'Create a WiFi QR code in seconds. No account, no subscription, no expiration. Works on all devices.',
    url: 'https://trulyfreeqr.com/wifi-qr-code-generator',
    siteName: 'Truly Free QR',
    type: 'website',
  },
}

const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'SoftwareApplication',
      name: 'Truly Free QR — WiFi QR Code Generator',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      url: 'https://trulyfreeqr.com/wifi-qr-code-generator',
      offers: { '@type': 'Offer', price: '0.00', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
      featureList: ['WiFi QR codes — free forever', 'Works on iPhone and Android', 'No account required', 'Download PNG or SVG', 'No subscription, no expiration'],
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'How do I create a WiFi QR code for free?',
          acceptedAnswer: { '@type': 'Answer', text: 'Go to Truly Free QR, select the WiFi tab, enter your network name (SSID), password, and security type (WPA2/WPA3). The QR code generates instantly. Download in PNG or SVG format — no account, no subscription, no expiration.' },
        },
        {
          '@type': 'Question',
          name: 'How does a WiFi QR code work on iPhone and Android?',
          acceptedAnswer: { '@type': 'Answer', text: 'On iPhone (iOS 11+), open the Camera app and point it at the QR code. A notification appears — tap it to connect automatically. On Android (9+), the same process works through the default camera app. No app download required on modern devices.' },
        },
        {
          '@type': 'Question',
          name: 'Is it safe to share WiFi passwords via QR code?',
          acceptedAnswer: { '@type': 'Answer', text: 'WiFi QR codes generated by Truly Free QR are static — the password is encoded directly in the QR pattern and never stored on our servers. The code works offline and requires no internet connection to function after download. Your password is never transmitted to any third party.' },
        },
        {
          '@type': 'Question',
          name: 'Can I use a WiFi QR code for my restaurant or hotel?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes. WiFi QR codes are ideal for restaurants, hotels, cafes, and offices. Print them on table cards, reception desks, or wall signs. When your WiFi password changes, generate a new code in seconds and reprint — the process takes under 60 seconds with no account required.' },
        },
      ],
    },
  ],
}

export default function WiFiQRPage() {
  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', background: '#f7fafc', minHeight: '100vh' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />

      <nav style={{ background: '#fff', borderBottom: '1px solid rgba(74,85,104,0.15)', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 56, position: 'sticky', top: 0, zIndex: 100 }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <img src="/logo.png" alt="TrulyFreeQR" style={{height:44,width:'auto'}} />
        </Link>
        <Link href="/" style={{ background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '8px 16px', fontSize: 13, fontWeight: 600, textDecoration: 'none' }}>Generate Free QR →</Link>
      </nav>

      <div style={{ maxWidth: 860, margin: '0 auto', padding: '48px 24px 80px' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(0,88,195,0.07)', border: '1px solid rgba(0,88,195,0.2)', borderRadius: 2, padding: '4px 10px', fontSize: 11, fontWeight: 700, color: '#0058c3', letterSpacing: '0.06em', marginBottom: 16 }}>✦ FREE — NO ACCOUNT — WORKS ON ALL DEVICES</div>
          <h1 style={{ fontSize: 36, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', lineHeight: 1.2, margin: '0 0 16px' }}>Free WiFi QR Code Generator — Guests Connect Instantly, No Password Typing</h1>
          <p style={{ fontSize: 16, color: '#4a5568', lineHeight: 1.7, margin: '0 0 24px' }}>Create a WiFi QR code in under 30 seconds. Guests scan with any iPhone or Android camera and connect automatically — no app, no typing, no friction. Download in PNG or SVG. Free forever, no account required.</p>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 28px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Create WiFi QR Code Free →</Link>
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 16px' }}>How to Create a WiFi QR Code — 3 Steps</h2>
          {[
            ['1. Select WiFi Tab', 'Go to the Truly Free QR generator and click the WiFi tab. Enter your network name (SSID), password, and security type — WPA2 for most home and business networks, WPA3 for newer routers.'],
            ['2. Generate and Preview', 'The QR code generates instantly as you type. Preview it on screen before downloading. The WiFi credentials are encoded directly in the QR pattern — no server storage, fully offline after download.'],
            ['3. Download and Print', 'Download in PNG (3000×3000px) for digital use or SVG vector for unlimited print scaling. Place on table cards, reception signage, or menu inserts. No account required, no expiration.'],
          ].map(([title, desc]) => (
            <div key={String(title)} style={{ display: 'flex', gap: 16, marginBottom: 20 }}>
              <div style={{ flexShrink: 0, width: 32, height: 32, background: 'linear-gradient(135deg,#0058c3,#0070f3)', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 13, fontWeight: 700 }}>{String(title)[0]}</div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: '#181c1e', marginBottom: 4 }}>{title}</div>
                <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.6 }}>{desc}</div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ background: '#f1f4f6', borderRadius: 8, padding: 32, marginBottom: 32 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 20px' }}>Compatible With All Devices</h2>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
            {[
              ['iPhone (iOS 11+)', 'Native camera app. Point and tap notification. No app download.'],
              ['Android (9+)', 'Default camera app. Instant connection prompt.'],
              ['Older Devices', 'Use any free QR scanner app from the App Store or Google Play.'],
            ].map(([title, desc]) => (
              <div key={title} style={{ background: '#fff', borderRadius: 8, padding: 16 }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#181c1e', marginBottom: 6 }}>{title}</div>
                <div style={{ fontSize: 12, color: '#4a5568', lineHeight: 1.6 }}>{desc}</div>
              </div>
            ))}
          </div>
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 24px' }}>Frequently Asked Questions</h2>
          {[
            ['How do I create a WiFi QR code for free?', 'Go to Truly Free QR, select the WiFi tab, enter your network name, password, and security type. The QR code generates instantly. Download in PNG or SVG — no account, no subscription, no expiration.'],
            ['How does a WiFi QR code work on iPhone and Android?', 'On iPhone (iOS 11+), open the Camera app and point it at the QR code. A notification appears — tap to connect. On Android (9+), the same process works through the default camera app. No app download required.'],
            ['Is it safe to share WiFi passwords via QR code?', 'WiFi QR codes from Truly Free QR are static — the password is encoded in the QR pattern and never stored on our servers. The code works offline and your password is never transmitted to any third party.'],
            ['Can I use a WiFi QR code for my restaurant or hotel?', 'Yes. Print on table cards, reception desks, or wall signs. When your password changes, generate a new code in under 60 seconds — no account required.'],
          ].map(([q, a], i) => (
            <div key={i} style={{ borderTop: i === 0 ? 'none' : '1px solid rgba(74,85,104,0.1)', paddingTop: i === 0 ? 0 : 20, marginTop: i === 0 ? 0 : 20 }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#181c1e', marginBottom: 8, letterSpacing: '-0.01em' }}>{q}</div>
              <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.7 }}>{a}</div>
            </div>
          ))}
        </div>

        <div style={{ textAlign: 'center', marginTop: 48 }}>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 32px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Create Your WiFi QR Code Free →</Link>
          <p style={{ fontSize: 12, color: '#718096', marginTop: 12 }}>No account · No credit card · No expiration · Forever free</p>
        </div>
      </div>

      <footer style={{ background: '#fff', borderTop: '1px solid rgba(74,85,104,0.15)', padding: '20px 24px', textAlign: 'center' }}>
        <div style={{ fontSize: 11, color: '#718096' }}>
          © 2026 Truly Free QR · Built by <a href="https://klickifyagency.com" target="_blank" rel="noopener noreferrer" style={{ color: '#0058c3', fontWeight: 600, textDecoration: 'none' }}>Klickify Agency</a>
        </div>
      </footer>
    </div>
  )
}
