import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Safe QR Code Generator — Built-in Phishing Protection | Truly Free QR',
  description: 'The only QR generator with Safe-Scan: verify destinations before redirecting. Protect your users from QR phishing (quishing) attacks. Free, no account required.',
  keywords: ['safe qr code generator', 'secure qr code maker', 'anti phishing qr code', 'safe scan qr', 'qr code phishing protection'],
  alternates: { canonical: 'https://trulyfreeqr.com/safe-qr-code-generator' },
  icons: {
    icon: [
      { url: "/favicon.ico?v=3" },
      { url: "/favicon-32.png?v=3", sizes: "32x32", type: "image/png" },
      { url: "/favicon-512.png?v=3", sizes: "512x512", type: "image/png" },
    ],
    apple: "/favicon-512.png?v=3",
  },
  openGraph: {
    title: 'Safe QR Code Generator — Built-in Phishing Protection',
    description: 'Generate QR codes with Safe-Scan protection. Verify destinations before redirecting. Free forever, no account required.',
    url: 'https://trulyfreeqr.com/safe-qr-code-generator',
    siteName: 'Truly Free QR',
    type: 'website',
  },
}

const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'SoftwareApplication',
      name: 'Truly Free QR — Safe QR Code Generator',
      applicationCategory: 'SecurityApplication',
      operatingSystem: 'Web',
      url: 'https://trulyfreeqr.com/safe-qr-code-generator',
      offers: { '@type': 'Offer', price: '0.00', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
      featureList: ['Safe-Scan phishing protection', 'Destination URL verification before redirect', 'Anti-quishing technology', 'Free forever, no account required', 'Real-time threat detection'],
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is QR code phishing (quishing)?',
          acceptedAnswer: { '@type': 'Answer', text: 'Quishing is a cyberattack where malicious QR codes redirect users to phishing websites designed to steal credentials, financial data, or install malware. QR phishing attacks grew 400% between 2023 and 2025, with 89.3% targeting credential theft. Unlike email phishing, QR codes bypass most email security filters because the malicious URL is hidden inside the image.' },
        },
        {
          '@type': 'Question',
          name: 'How does Safe-Scan protect users from QR phishing?',
          acceptedAnswer: { '@type': 'Answer', text: 'Every dynamic QR code generated by Truly Free QR includes Safe-Scan protection. Before executing the redirect, our system verifies the destination URL against threat intelligence databases. Users can also preview the destination URL before being redirected, giving them full transparency and control over where the code leads.' },
        },
        {
          '@type': 'Question',
          name: 'How can I tell if a QR code is safe to scan?',
          acceptedAnswer: { '@type': 'Answer', text: 'Look for QR codes generated by trusted sources with visible Safe-Scan badges. Before scanning unknown QR codes, use a QR scanner app that previews the destination URL. Never scan QR codes from unsolicited emails, stickers placed over legitimate codes, or unfamiliar locations. Truly Free QR codes display the destination URL before redirecting.' },
        },
        {
          '@type': 'Question',
          name: 'Is it safe to use QR codes for business?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes, when generated through a secure platform. Truly Free QR provides Safe-Scan protection on all dynamic codes, destination URL preview before redirect, and HTTPS-encrypted redirect infrastructure. This makes our codes safe for restaurants, retail, healthcare, and any business use case.' },
        },
      ],
    },
  ],
}

export default function SafeQRPage() {
  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', background: '#f7fafc', minHeight: '100vh' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />

      <nav style={{ background: '#fff', borderBottom: '1px solid rgba(74,85,104,0.15)', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 56, position: 'sticky', top: 0, zIndex: 100 }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <img src="/logo.png" alt="TrulyFreeQR" style={{height:44,width:'auto'}} />
        </Link>
        <Link href="/" style={{ background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '8px 16px', fontSize: 13, fontWeight: 600, textDecoration: 'none' }}>Generate Safe QR →</Link>
      </nav>

      <div style={{ maxWidth: 860, margin: '0 auto', padding: '48px 24px 80px' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.3)', borderRadius: 2, padding: '4px 10px', fontSize: 11, fontWeight: 700, color: '#16a34a', letterSpacing: '0.06em', marginBottom: 16 }}>✓ SAFE-SCAN PROTECTED — ANTI-PHISHING BUILT-IN</div>
          <h1 style={{ fontSize: 36, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', lineHeight: 1.2, margin: '0 0 16px' }}>Safe QR Code Generator — Built-in Phishing Protection for Every Code</h1>
          <p style={{ fontSize: 16, color: '#4a5568', lineHeight: 1.7, margin: '0 0 24px' }}>The only free QR generator with Safe-Scan technology. Every dynamic code verifies its destination before redirecting — protecting your users from QR phishing (quishing) attacks that grew 400% since 2023. Free forever, no account required.</p>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 28px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Generate a Safe QR Code Free →</Link>
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 16px' }}>The QR Phishing Threat — By The Numbers</h2>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12, marginBottom: 20 }}>
            {[
              ['400%', 'Growth in QR phishing attacks 2023–2025'],
              ['89.3%', 'Of attacks target credential theft'],
              ['$1B+', 'Estimated annual losses from quishing'],
            ].map(([stat, desc]) => (
              <div key={stat} style={{ background: '#f1f4f6', borderRadius: 8, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 28, fontWeight: 700, color: '#0058c3', letterSpacing: '-0.02em', marginBottom: 4 }}>{stat}</div>
                <div style={{ fontSize: 12, color: '#718096', lineHeight: 1.5 }}>{desc}</div>
              </div>
            ))}
          </div>
          <p style={{ fontSize: 14, color: '#4a5568', lineHeight: 1.7, margin: 0 }}>QR phishing bypasses email security filters because the malicious URL is hidden inside an image. Attackers place stickers over legitimate QR codes in restaurants, parking meters, and public spaces. Truly Free QR addresses this with Safe-Scan — destination verification before every redirect.</p>
        </div>

        <div style={{ background: '#f1f4f6', borderRadius: 8, padding: 32, marginBottom: 32 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 20px' }}>How Safe-Scan Works</h2>
          {[
            ['Destination Verification', 'Before executing any redirect, our system checks the destination URL against threat intelligence databases to detect known phishing domains and malicious endpoints.'],
            ['URL Preview', 'Users can see the full destination URL before being redirected — full transparency, zero blind redirects. This alone eliminates the primary attack vector of QR phishing.'],
            ['HTTPS Infrastructure', 'All redirects route through our encrypted VPS infrastructure. No plain HTTP redirects, no mixed content, no insecure endpoints.'],
            ['Real-time Monitoring', 'Our redirect engine logs anomalous scan patterns that may indicate a compromised code — bulk scans from unusual locations trigger automatic review.'],
          ].map(([title, desc]) => (
            <div key={title} style={{ display: 'flex', gap: 16, marginBottom: 20, background: '#fff', borderRadius: 8, padding: 16 }}>
              <div style={{ flexShrink: 0, width: 32, height: 32, background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.3)', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#16a34a', fontSize: 14, fontWeight: 700 }}>✓</div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: '#181c1e', marginBottom: 4 }}>{title}</div>
                <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.6 }}>{desc}</div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ background: '#fff', borderRadius: 8, padding: 32, marginBottom: 32, boxShadow: '0px 8px 24px rgba(24,28,30,0.06)' }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#181c1e', letterSpacing: '-0.02em', margin: '0 0 24px' }}>Frequently Asked Questions</h2>
          {[
            ['What is QR code phishing (quishing)?', 'Quishing is a cyberattack where malicious QR codes redirect users to phishing websites. QR phishing grew 400% between 2023 and 2025, with 89.3% targeting credential theft. Unlike email phishing, QR codes bypass most security filters because the URL is hidden inside an image.'],
            ['How does Safe-Scan protect users from QR phishing?', 'Every dynamic QR code from Truly Free QR includes Safe-Scan protection. Before executing the redirect, our system verifies the destination URL against threat databases. Users can preview the destination URL before being redirected.'],
            ['How can I tell if a QR code is safe to scan?', 'Look for QR codes from trusted sources with Safe-Scan badges. Before scanning unknown codes, use a QR scanner that previews the destination URL. Never scan QR codes from unsolicited emails or stickers placed over legitimate codes.'],
            ['Is it safe to use QR codes for business?', 'Yes, when generated through a secure platform. Truly Free QR provides Safe-Scan protection, destination URL preview, and HTTPS-encrypted infrastructure on all dynamic codes.'],
          ].map(([q, a], i) => (
            <div key={i} style={{ borderTop: i === 0 ? 'none' : '1px solid rgba(74,85,104,0.1)', paddingTop: i === 0 ? 0 : 20, marginTop: i === 0 ? 0 : 20 }}>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#181c1e', marginBottom: 8, letterSpacing: '-0.01em' }}>{q}</div>
              <div style={{ fontSize: 13, color: '#4a5568', lineHeight: 1.7 }}>{a}</div>
            </div>
          ))}
        </div>

        <div style={{ textAlign: 'center', marginTop: 48 }}>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'linear-gradient(135deg,#0058c3,#0070f3)', color: '#fff', borderRadius: 4, padding: '14px 32px', fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>Generate Your Safe QR Code Free →</Link>
          <p style={{ fontSize: 12, color: '#718096', marginTop: 12 }}>Safe-Scan protected · No account · No subscription · Forever free</p>
        </div>
      </div>

      <footer style={{ background: '#fff', borderTop: '1px solid rgba(74,85,104,0.15)', padding: '20px 24px', textAlign: 'center' }}>
        <div style={{ fontSize: 11, color: '#718096' }}>
          © 2026 Truly Free QR · Built by <a href="https://klickifyagency.com" target="_blank" rel="noopener noreferrer" style={{ color: '#0058c3', fontWeight: 600, textDecoration: 'none' }}>Klickify Agency</a>
        </div>
      </footer>
    </div>
  )
}
